[alias]
b = "build"
t = "test --test *"
r = "run -- --dev -lerror,ethink=debug"

[env]
FLIPPER_PATH = { value = "dapp/contracts/flipper.ink/Cargo.toml", relative = true, force = true }
ERC20_PATH = { value = "dapp/contracts/erc20.ink/Cargo.toml", relative = true, force = true }
ALITH_ADDRESS = "0xf24FF3a9CF04c71Dbc94D0b566f7A27B94566cac"
ALITH_KEY = "0x5fb92d6e98884f76de468fa3f6278f8807c48bebc13595d45af5bdc4da702133"
BALTATHAR_ADDRESS = "0x3Cd0A705a2DC65e5b1E1205896BaA2be8A07c6e0"
BALTATHAR_KEY = "0x8075991ce870b93a8870eca0c0f91913d12f47948ca0fd25b49c6fa7cdbeee8b"
